import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import logo from "../../public/assets/Logo_OCTOBIT_Logo_Branco_SIMBOLO.png"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Octobit Jr.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
